version: "3.9"
services:
  myfitapp:
    container_name: myfitapp
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - myfitapp_net
    volumes:
      - workouts_data:/data

networks:
  myfitapp_net: {}

volumes:
  workouts_data:
