# fly.toml app configuration file generated for ferretdb on 2023-08-27T10:56:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ferretdb"
primary_region = "mad"

[build]

[[services]]
internal_port = 27017
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[env]
FERRETDB_POSTGRESQL_URL = "postgres://my-fitapp-postgres.internal:5432/ferretdb"
