# fly.toml app configuration file generated for my-fitapp-postgres on 2023-08-27T10:27:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-fitapp-postgres"
primary_region = "mad"

[build]

[[services]]
internal_port = 5432
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[env]
POSTGRES_USER = "username"
POSTGRES_PASSWORD = "password"
POSTGRES_DB = "ferretdb"
